function [ys_, params, info] = dtcgap_steadystate2(ys_, exo_, params)
% Steady state generated by Dynare preprocessor
    info = 0;
    ys_(4)=0;
    ys_(5)=ys_(4);
    ys_(2)=params(10);
    ys_(3)=(ys_(2)^(-params(1))/(1-params(2)))^(1/(1-params(4)));
    ys_(1)=ys_(3)+1/(ys_(3)^(params(4)-1)-ys_(2)^(-params(1))*ys_(5)*params(2));
    % Auxiliary equations
    check_=0;
end
